### PR TITLE
Fix Issue #20

### LINKED ISSUE #20: undefined method `rindex' for nil:NilClass when using resize: true
Hello! Thanks for creating this gem, it's been very useful for our team.

We are experiencing a bug where table resize raises an exception. The bug only occurs when terminal size is small enough that table resize is required:

    $ stty size
    21 81
    $ ruby /tmp/test2.rb 
    /usr/local/rvm/gems/ruby-2.3.6/gems/strings-0.1.1/lib/strings/truncate.rb:59:in `truncate': undefined method `rindex' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.6/gems/strings-0.1.1/lib/strings.rb:98:in `truncate'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operation/truncation.rb:38:in `call'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:59:in `block (4 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:58:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:58:in `block (3 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:57:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:57:in `block (2 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `each_with_index'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `block in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `each_with_index'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer/basic.rb:203:in `render'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer.rb:77:in `render'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer.rb:99:in `render_with'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table.rb:452:in `render_with'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table.rb:426:in `render'
        from /tmp/test2.rb:11:in `<main>'

Here is a script to reproduce:

    #!/usr/bin/env ruby
    require 'tty-table'
    table = TTY::Table.new(header: ['my header', 'a', 'b', 'c', 'd'])
    string = 'some long data that must be wrapped'
    table << [string, '', 'data', string, string]
    puts table.render(:unicode, resize: true)

### PR DESCRIPTION
**Pull request by slowbro**
### Describe the change
Partially fixes #20 - requires the strings patch here: piotrmurach/strings#8

### Why are we doing this?
Fixes the handling of too-small terminals, or very small supplied widths. previously the `width` was allowed to go negative which would make Strings#truncate throw an error. This fixes the negative numbers, and the strings patch fixes a column width of 1.

### Benefits
Covers an unhandled exception when using resize:true.

### Drawbacks
Tests were changed, as the output from the renderers is slightly different with the clamped width. 

### Requirements
Put an X between brackets on each line if you have done the item:
[x] Tests written & passing locally?
[x] Code style checked?
[x] Rebased with `master` branch?
[x] Documentation updated?

### CODE REVIEW

File: lib/tty/table/column_constraint.rb [hunk 1]
```diff
@@ -141,7 +141,8 @@ def shrink
         ratio       = ((natural_width - renderer.width) / column_size.to_f).ceil
 
         widths = (0...column_size).reduce([]) do |lengths, col|
-          lengths + [renderer.column_widths[col] - ratio]
+          width = (renderer.column_widths[col] - ratio).clamp(minimum_width, renderer.width)
```
Comment (piotrmurach) [inline lib/tty/table/column_constraint.rb]: Could you please replace `clamp` with ternary comparison? The reason being, for now I'd like to keep the gem working on older Rubies if possible and it seems `calmp` was added in `2.4.0`. Sorry for this restriction.

Comment (slowbro) [reply lib/tty/table/column_constraint.rb]: Yeah! I worried that would be a problem. I'll replace it.

Comment (piotrmurach) [reply lib/tty/table/column_constraint.rb]: I wish I could accept `clamp`- it's so much nicer and expressive.

**Comment by slowbro** [comment]
Done.
